### ISSUE TITLE
packages/apps/RealmeParts/res/layout/doze.xml:25: error: resource layout/switch_bar (aka com.realmeparts:layout/switch_bar) not found.                  error: failed linking file resources.

### ISSUE THREAD

**Issue by CyberJalagam** [HyperTeam/packages_apps_RealmeParts#1]

**Comment by 4j17h** [comment]
You should clone DeviceSettings resources from LineageOS

> git clone https://github.com/LineageOS/android_packages_resources_devicesettings.git packages/resources/devicesettings/

**Comment by CyberJalagam** [comment]
Omk will see morning :)

**Comment by 4j17h** [comment]
> Omk will see morning :)

Sure, let me know how it goes.

**Comment by CyberJalagam** [comment]
> > Omk will see morning :)
> 
> Sure, let me know how it goes.

packages/resources/devicesettings/res/values/styles.xml:54: error: style attribute 'attr/preferenceCategoryTitleTextColor (aka com.realmeparts:attr/preferenceCategoryTitleTextColor)' not found.

Wah wah

**Comment by CyberJalagam** [comment]
looks like this dosen't build for A10

**Comment by karthick111** [comment]
@CyberJalagam probably you may have seen lineage-18.1 as branch which is android 11.
