### ISSUE TITLE
can not find symbol R

### ISSUE THREAD

**Issue by killah78** [HyperTeam/packages_apps_RealmeParts#5]
Hi, 
I currrently try to compile (on a Linux Debian bookworm) a Lineage-21 for a Realme samurai. 
When I include RealmeParts, I get the following errors:
`packages/apps/RealmeParts/src/com/realmeparts/DeviceSettingsActivity.java:24: error: cannot find symbol
import com.android.settingslib.widget.R;
                                     ^
  symbol:   class R
  location: package com.android.settingslib.widget
packages/apps/RealmeParts/src/com/realmeparts/doze/DozeSettingsActivity.java:23: error: cannot find symbol
import com.android.settingslib.widget.R;
                                     ^
  symbol:   class R
  location: package com.android.settingslib.widget
packages/apps/RealmeParts/src/com/realmeparts/doze/DozeSettingsFragment.java:37: error: cannot find symbol
import com.android.settingslib.widget.OnMainSwitchChangeListener;
                                     ^
  symbol:   class OnMainSwitchChangeListener
  location: package com.android.settingslib.widget
packages/apps/RealmeParts/src/com/realmeparts/doze/DozeSettingsFragment.java:42: error: cannot find symbol
        OnMainSwitchChangeListener {
        ^
  symbol: class OnMainSwitchChangeListener
packages/apps/RealmeParts/src/com/realmeparts/doze/DozeSettingsActivity.java:33: error: package R does not exist
        getFragmentManager().beginTransaction().replace(R.id.content_frame,
                                                         ^
packages/apps/RealmeParts/src/com/realmeparts/doze/DozeSettingsFragment.java:65: error: incompatible types: DozeSettingsFragment cannot be converted to OnCheckedChangeListener
        mSwitchBar.addOnSwitchChangeListener(this);
                                             ^
packages/apps/RealmeParts/src/com/realmeparts/doze/DozeSettingsFragment.java:118: error: method does not override or implement a method from a supertype
    @Override
    ^
packages/apps/RealmeParts/src/com/realmeparts/switch/BatterySavingModeSwitch.java:66: error: cannot find symbol
        DeviceSettings.mRefreshRate90.setChecked(RefreshRateSwitch.isCurrentlyEnabled(mContext));
                      ^
  symbol:   variable mRefreshRate90
  location: class DeviceSettings
packages/apps/RealmeParts/src/com/realmeparts/switch/BatterySavingModeSwitch.java:67: error: cannot find symbol
        DeviceSettings.mRefreshRate60.setChecked(!RefreshRateSwitch.isCurrentlyEnabled(mContext));
                      ^
  symbol:   variable mRefreshRate60
  location: class DeviceSettings
`
When I exclude Realmeparts, it runs without errors. What do I miss here?
PS: I get the same issue when I try compiling crdroid. 
Thanks and best regards

**Comment by karthick111** [comment]
Fixes has been rolled out, check out.
